-- ═════════════════════════════════════════════════════════════
--  BASE DE DATOS DURO — F19(c) PARTE 4: Optimización de Índices y Partición Optimizada del Rendimiento Multi-Tenant
-- Puede ejecutarse después de la migración 010 (RLS activo) y 011 (checks/triggers)\n-- ═════════════════════════════════════════════════════════════\n\n-- 1. ÍNDICES SUPLETORIOS ACTUALES EN TABLAS DELTA: eliminar índices granulares para eliminación de datos duplicados\n-- Estos índices actuales ``_tenant`` son costosos en almacenamiento, innecesarios para el rendimiento real.\n-- Los patrones de consulta legítimos se centran en los tres siguientes:\n\n--   - "buscar leads por tenant_id + status" (trending en production)\n--   - "buscar leads por tenant_id + ai_category" (benchmarking)\n--   - "buscar leads por tenant_id + created_at DESC" (feed/post list)
--   - ``score`` por ambos lead_id y tenant_id (cada score pertenece a lead y necesita garantizar tenant de lead)\n\n-- Por lo tanto, eliminamos índices individuales innecesarios y creamos N índices compuestos que satisfacen\n-- requerimientos de consulta de producción sin sobrecargar el almacenamiento.\n\n-- 1.1 Índices de ``leads``{\nDROP INDEX IF EXISTS idx_leads_tenant ON leads;\nDROP INDEX IF EXISTS idx_leads_email ON leads;\nDROP INDEX IF EXISTS idx_leads_status ON leads;\nDROP INDEX IF EXISTS idx_leads_category ON leads;\nDROP INDEX IF EXISTS idx_leads_created ON leads;\n
-- 1.2 Índices compuestos optimizados para ``leads`` para esquemas de consultas reales.\nCREATE INDEX idx_leads_tenant_status ON leads(tenant_id, status);\nCREATE INDEX idx_leads_tenant_category ON leads(tenant_id, ai_category);\nCREATE INDEX idx_leads_tenant_created_at ON leads(tenant_id, created_at DESC);\n\n-- 1.3 Optimización segura de ``scores`` {
DROP INDEX IF EXISTS idx_scores_lead ON scores;\nDROP INDEX IF EXISTS idx_scores_tenant ON scores;\n\nCREATE INDEX idx_scores_lead ON scores(lead_id);\nCREATE INDEX idx_scores_lead_tenant ON scores(lead_id, tenant_id);\n\n-- 1.4 Estrategia óptima de ``workflow_runs`` {
DROP INDEX IF EXISTS idx_workflow_runs_tenant ON workflow_runs;\nDROP INDEX IF EXISTS idx_workflow_runs_status ON workflow_runs;\nDROP INDEX IF EXISTS idx_workflow_runs_started ON workflow_runs;\n\nCREATE INDEX idx_workflow_runs_tenant_status ON workflow_runs(tenant_id, status);\nCREATE INDEX idx_workflow_runs_tenant_started_at ON workflow_runs(tenant_id, created_at DESC);\n\n-- 1.5 Optimización típica de ``users`` {
DROP INDEX IF EXISTS idx_users_tenant ON users;\nDROP INDEX IF EXISTS idx_users_email ON users;\n\nCREATE INDEX idx_users_tenant ON users(tenant_id);\nCREATE INDEX idx_users_email ON users(email);\n\n-- 1.6 Índices restantes de ``error_log`` — no cambian pero mantenerse para logs bajo RLS.\n-- 1.7 Índices adicionales de ``audit_log`` — mantener para búsqueda de auditoría densa.\n-- 1.8 Índices secundarios de ``lead_log`` — mantenimiento independiente.\n\n-- 2. ÍNDICES DE INTEGRIDAD MULTI-TENANT — lo más estrecho posible para evitar escaneos full table.
\n-- 2.1 ``tenant_settings`` {
CREATE INDEX idx_tenant_settings_tenant_key ON tenant_settings(tenant_id, key);\n\n-- 2.2 ``lead_log`` necesita búsqueda por tenant_id + email (dedup) y formateo.\nCREATE INDEX idx_lead_log_tenant_email ON lead_log(tenant_id, email);\nCREATE INDEX idx_lead_log_tenant_created_at ON lead_log(tenant_id, created_at DESC);\n\n-- 2.3 ``audit_log`` composite — tenant + sort + 1 domain último objetivo de performance.\nCREATE UNIQUE INDEX idx_audit_log_unique_composite ON audit_log(tenant_id, resource_id, action, created_at);\n\n-- 3. ``check`` y ``trigger`` integrados en migración aparte (011), no índice aquí.\n\n-- 4. VALIDACIÓN FINAL DE REDUCCIÓN DE ÍNDICES — punto medio realista:\n--   - Reemplazamos 10 índices viejos con 13 índices compuestos correctamente construidos.\n--   - Los índices compuestos eliminan costosos primeros N niveles de índice directo para consultas típicas.\n--   - Los índices mantienen segmentos organizados y separados por tabla.\n\nCOMMIT;\n